#!/bin/bash

function main() {
	#for basic pip
	python -m pip install -r requirements.txt

	#for jax gpu
	python -m pip install -U jaxlib==0.3.22+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

	#install t5 because they said to do so
	python -m pip install t5

	#fix flax version
	python -m pip install --upgrade flax==0.5.3

	#stuff for ca-certs
	python -m pip install certifi
	cert_pth=$(python -m certi)
	python -m pip config set global.cert ${cert_pth}
	python -m pip config list
	conda config --set ssl_verify ${cert_pth}
	conda config --show ssl_verify

}

main $@
